name: Build and run Postman APIs with Newman

on:
  push:
    branches: main

jobs:
  build-and-run:
    name: Build and run APIs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Musement APIs in Newman CI
      run: docker run -t -v "/home/runner/work/musement-apis/musement-apis/config:/opt/newman/src/config" --rm aurelienlair/newman:1.1.0

    # https://github.com/rtCamp/action-slack-notify
    - name: Musement APIs ran in Newman CI has succeeded
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_COLOR: '#008000'
        SLACK_ICON: ${{ secrets.SLACK_ICON }}
        SLACK_MESSAGE: "Let's rock!!!"
        SLACK_TITLE: 'Musement APIs Newman execution report: :done_ball:'
        SLACK_USERNAME: Github-bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Musement APIs ran in Newman CI has failed
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: ${{ secrets.SLACK_ICON }}
        SLACK_MESSAGE: "Houston we have a problem..(it's probably your found) check it out => https://github.com/aurelienlair/musement-apis/actions"
        SLACK_TITLE: 'Musement APIs Newman execution report: :alert:'
        SLACK_USERNAME: Github-bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}